version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
