### crear parroquia
POST http://localhost:3000/api/parroquias
Content-Type: application/json

{
    "name":"santa lucia",
    "address": "Plaza de Santa Lucia",
    "postalCode": "5411"
}
### crear sacerdote
POST http://localhost:3000/api/sacerdote
Content-Type: application/json

{
    "name":"Miguel",
    "lastname":"perez",
    "postalCode":"5411",
    "phone":"1234",
    "imagen":"https://res.cloudinary.com/doh6fzrdq/image/upload/v1669303568/cld-sample-2.jpg",
    "parroquia":"637f93c0901f1f1e0dbdcc3b",
    "nombramiento":["Presbitero"]
}
### get sacerdotes
GET http://localhost:3000/api/sacerdotes
Content-Type: application/json

### get parroquias
GET http://localhost:3000/api/parroquias
Content-Type: application/json

### get sacerdote
GET http://localhost:3000/api/sacerdotes/6372ad9b458a43abd62503db
Content-Type: application/json

### get sacerdote
GET https://ec6a-200-114-98-6.sa.ngrok.io/api/sacerdote
Content-Type: application/json

### borrar sacerdote
DELETE  http://localhost:3000/api/sacerdotes/
Content-Type: application/json

{
    "name":"Gustavo",
    "lastname":"Aranciba",
    "postalcode":"5411",
    "parroquia":"6342b309e0fd35adfd10c227"
}

### contenido session
http://localhost:3000/api/auth/session

### signin
http://localhost:3000/api/auth/signin

### datos de sesión
http://0.0.0.0:3000/api/auth/session